"""empty message

Revision ID: 7b1bb7553200
Revises: f9beb06432eb
Create Date: 2021-07-20 18:13:27.896995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1bb7553200'
down_revision = 'f9beb06432eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('image_url', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'image_url')
    # ### end Alembic commands ###
