"""empty message

Revision ID: ccef98506768
Revises: 289310cb664f
Create Date: 2021-07-20 13:15:55.594622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccef98506768'
down_revision = '289310cb664f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_user',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.alter_column('playlists', 'playlist_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_constraint('playlists_playlist_name_key', 'playlists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('playlists_playlist_name_key', 'playlists', ['playlist_name'])
    op.alter_column('playlists', 'playlist_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_table('follow_user')
    # ### end Alembic commands ###
